### ISSUE TITLE
Arrays in resources are broken

### ISSUE THREAD

**Issue by abalmos** [OADA/oada-api-server#5]
Consider the valleyix dbsetup and the path: 
https://localhost:3000/bookmarks/irrigation/machines/list/0928sdfk9j/configuration

The `oada-formats` example for this mediatype has `EndGunList` as an array. It appears `oada-api-server` is turning it into an object. I traced it as far as I could and it seems that the resource that is `put` to the db handler has an array for `EndGnuList`

**Comment by aultac** [comment]
I will track down why it's ending up as an object instead of an array.  On a related note, the server does not currently support storing arrays as top-level resources since they need _id, _rev, and _meta in them.  I'm going to make the resources-handler wrap top-level arrays with an object and then extract the array on GET's.  This should not affect storing arrays as sub-keys, which should have already been working.  I will add tests for this as well.
